/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Fm23RouteImport } from './routes/fm23'
import { Route as F125RouteImport } from './routes/f125'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AccRouteImport } from './routes/acc'
import { Route as AcEvoRouteImport } from './routes/ac-evo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Fm23IndexRouteImport } from './routes/fm23/index'
import { Route as F125IndexRouteImport } from './routes/f125/index'
import { Route as DashIndexRouteImport } from './routes/dash.index'
import { Route as AccIndexRouteImport } from './routes/acc/index'
import { Route as AcEvoIndexRouteImport } from './routes/ac-evo/index'
import { Route as Fm23TunesRouteImport } from './routes/fm23/tunes'
import { Route as Fm23TracksRouteImport } from './routes/fm23/tracks'
import { Route as Fm23SetupRouteImport } from './routes/fm23/setup'
import { Route as Fm23SessionsRouteImport } from './routes/fm23/sessions'
import { Route as Fm23RawRouteImport } from './routes/fm23/raw'
import { Route as Fm23LiveRouteImport } from './routes/fm23/live'
import { Route as Fm23CompareRouteImport } from './routes/fm23/compare'
import { Route as Fm23ChatsRouteImport } from './routes/fm23/chats'
import { Route as Fm23CarsRouteImport } from './routes/fm23/cars'
import { Route as Fm23AnalyseRouteImport } from './routes/fm23/analyse'
import { Route as F125TunesRouteImport } from './routes/f125/tunes'
import { Route as F125TracksRouteImport } from './routes/f125/tracks'
import { Route as F125SetupRouteImport } from './routes/f125/setup'
import { Route as F125SessionsRouteImport } from './routes/f125/sessions'
import { Route as F125RawRouteImport } from './routes/f125/raw'
import { Route as F125LiveRouteImport } from './routes/f125/live'
import { Route as F125CompareRouteImport } from './routes/f125/compare'
import { Route as F125ChatsRouteImport } from './routes/f125/chats'
import { Route as F125CarsRouteImport } from './routes/f125/cars'
import { Route as F125AnalyseRouteImport } from './routes/f125/analyse'
import { Route as DashCombo2RouteImport } from './routes/dash.combo-2'
import { Route as DashCombo1RouteImport } from './routes/dash.combo-1'
import { Route as AccTracksRouteImport } from './routes/acc/tracks'
import { Route as AccSetupRouteImport } from './routes/acc/setup'
import { Route as AccSessionsRouteImport } from './routes/acc/sessions'
import { Route as AccRawRouteImport } from './routes/acc/raw'
import { Route as AccLiveRouteImport } from './routes/acc/live'
import { Route as AccCompareRouteImport } from './routes/acc/compare'
import { Route as AccChatsRouteImport } from './routes/acc/chats'
import { Route as AccCarsRouteImport } from './routes/acc/cars'
import { Route as AccAnalyseRouteImport } from './routes/acc/analyse'
import { Route as AcEvoTracksRouteImport } from './routes/ac-evo/tracks'
import { Route as AcEvoSessionsRouteImport } from './routes/ac-evo/sessions'
import { Route as AcEvoRawRouteImport } from './routes/ac-evo/raw'
import { Route as AcEvoLiveRouteImport } from './routes/ac-evo/live'
import { Route as AcEvoCompareRouteImport } from './routes/ac-evo/compare'
import { Route as AcEvoChatsRouteImport } from './routes/ac-evo/chats'
import { Route as AcEvoCarsRouteImport } from './routes/ac-evo/cars'
import { Route as AcEvoAnalyseRouteImport } from './routes/ac-evo/analyse'
import { Route as Fm23TunesIndexRouteImport } from './routes/fm23/tunes/index'
import { Route as Fm23SetupIndexRouteImport } from './routes/fm23/setup/index'
import { Route as F125TunesIndexRouteImport } from './routes/f125/tunes/index'
import { Route as F125SetupIndexRouteImport } from './routes/f125/setup/index'
import { Route as AccSetupIndexRouteImport } from './routes/acc/setup/index'
import { Route as Fm23TunesNewRouteImport } from './routes/fm23/tunes/new'
import { Route as Fm23TunesCatalogRouteImport } from './routes/fm23/tunes/catalog'
import { Route as Fm23SetupProfileIdRouteImport } from './routes/fm23/setup/$profileId'
import { Route as Fm23LivePitRouteImport } from './routes/fm23/live/pit'
import { Route as Fm23LiveDriverRouteImport } from './routes/fm23/live/driver'
import { Route as Fm23CarsCarOrdinalRouteImport } from './routes/fm23/cars_.$carOrdinal'
import { Route as Fm23TunesEditTuneIdRouteImport } from './routes/fm23/tunes/edit.$tuneId'

const Fm23Route = Fm23RouteImport.update({
  id: '/fm23',
  path: '/fm23',
  getParentRoute: () => rootRouteImport,
} as any)
const F125Route = F125RouteImport.update({
  id: '/f125',
  path: '/f125',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AccRoute = AccRouteImport.update({
  id: '/acc',
  path: '/acc',
  getParentRoute: () => rootRouteImport,
} as any)
const AcEvoRoute = AcEvoRouteImport.update({
  id: '/ac-evo',
  path: '/ac-evo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Fm23IndexRoute = Fm23IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Fm23Route,
} as any)
const F125IndexRoute = F125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125Route,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/dash/',
  path: '/dash/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccIndexRoute = AccIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccRoute,
} as any)
const AcEvoIndexRoute = AcEvoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcEvoRoute,
} as any)
const Fm23TunesRoute = Fm23TunesRouteImport.update({
  id: '/tunes',
  path: '/tunes',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23TracksRoute = Fm23TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23SetupRoute = Fm23SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23SessionsRoute = Fm23SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23RawRoute = Fm23RawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23LiveRoute = Fm23LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23CompareRoute = Fm23CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23ChatsRoute = Fm23ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23CarsRoute = Fm23CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23AnalyseRoute = Fm23AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => Fm23Route,
} as any)
const F125TunesRoute = F125TunesRouteImport.update({
  id: '/tunes',
  path: '/tunes',
  getParentRoute: () => F125Route,
} as any)
const F125TracksRoute = F125TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => F125Route,
} as any)
const F125SetupRoute = F125SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => F125Route,
} as any)
const F125SessionsRoute = F125SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => F125Route,
} as any)
const F125RawRoute = F125RawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => F125Route,
} as any)
const F125LiveRoute = F125LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => F125Route,
} as any)
const F125CompareRoute = F125CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => F125Route,
} as any)
const F125ChatsRoute = F125ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => F125Route,
} as any)
const F125CarsRoute = F125CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => F125Route,
} as any)
const F125AnalyseRoute = F125AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => F125Route,
} as any)
const DashCombo2Route = DashCombo2RouteImport.update({
  id: '/dash/combo-2',
  path: '/dash/combo-2',
  getParentRoute: () => rootRouteImport,
} as any)
const DashCombo1Route = DashCombo1RouteImport.update({
  id: '/dash/combo-1',
  path: '/dash/combo-1',
  getParentRoute: () => rootRouteImport,
} as any)
const AccTracksRoute = AccTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AccRoute,
} as any)
const AccSetupRoute = AccSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AccRoute,
} as any)
const AccSessionsRoute = AccSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AccRoute,
} as any)
const AccRawRoute = AccRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => AccRoute,
} as any)
const AccLiveRoute = AccLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AccRoute,
} as any)
const AccCompareRoute = AccCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AccRoute,
} as any)
const AccChatsRoute = AccChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AccRoute,
} as any)
const AccCarsRoute = AccCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AccRoute,
} as any)
const AccAnalyseRoute = AccAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => AccRoute,
} as any)
const AcEvoTracksRoute = AcEvoTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoSessionsRoute = AcEvoSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoRawRoute = AcEvoRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoLiveRoute = AcEvoLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoCompareRoute = AcEvoCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoChatsRoute = AcEvoChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoCarsRoute = AcEvoCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AcEvoRoute,
} as any)
const AcEvoAnalyseRoute = AcEvoAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => AcEvoRoute,
} as any)
const Fm23TunesIndexRoute = Fm23TunesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Fm23TunesRoute,
} as any)
const Fm23SetupIndexRoute = Fm23SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Fm23SetupRoute,
} as any)
const F125TunesIndexRoute = F125TunesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125TunesRoute,
} as any)
const F125SetupIndexRoute = F125SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => F125SetupRoute,
} as any)
const AccSetupIndexRoute = AccSetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccSetupRoute,
} as any)
const Fm23TunesNewRoute = Fm23TunesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => Fm23TunesRoute,
} as any)
const Fm23TunesCatalogRoute = Fm23TunesCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => Fm23TunesRoute,
} as any)
const Fm23SetupProfileIdRoute = Fm23SetupProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => Fm23SetupRoute,
} as any)
const Fm23LivePitRoute = Fm23LivePitRouteImport.update({
  id: '/pit',
  path: '/pit',
  getParentRoute: () => Fm23LiveRoute,
} as any)
const Fm23LiveDriverRoute = Fm23LiveDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => Fm23LiveRoute,
} as any)
const Fm23CarsCarOrdinalRoute = Fm23CarsCarOrdinalRouteImport.update({
  id: '/cars_/$carOrdinal',
  path: '/cars/$carOrdinal',
  getParentRoute: () => Fm23Route,
} as any)
const Fm23TunesEditTuneIdRoute = Fm23TunesEditTuneIdRouteImport.update({
  id: '/edit/$tuneId',
  path: '/edit/$tuneId',
  getParentRoute: () => Fm23TunesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ac-evo': typeof AcEvoRouteWithChildren
  '/acc': typeof AccRouteWithChildren
  '/dev': typeof DevRoute
  '/f125': typeof F125RouteWithChildren
  '/fm23': typeof Fm23RouteWithChildren
  '/ac-evo/analyse': typeof AcEvoAnalyseRoute
  '/ac-evo/cars': typeof AcEvoCarsRoute
  '/ac-evo/chats': typeof AcEvoChatsRoute
  '/ac-evo/compare': typeof AcEvoCompareRoute
  '/ac-evo/live': typeof AcEvoLiveRoute
  '/ac-evo/raw': typeof AcEvoRawRoute
  '/ac-evo/sessions': typeof AcEvoSessionsRoute
  '/ac-evo/tracks': typeof AcEvoTracksRoute
  '/acc/analyse': typeof AccAnalyseRoute
  '/acc/cars': typeof AccCarsRoute
  '/acc/chats': typeof AccChatsRoute
  '/acc/compare': typeof AccCompareRoute
  '/acc/live': typeof AccLiveRoute
  '/acc/raw': typeof AccRawRoute
  '/acc/sessions': typeof AccSessionsRoute
  '/acc/setup': typeof AccSetupRouteWithChildren
  '/acc/tracks': typeof AccTracksRoute
  '/dash/combo-1': typeof DashCombo1Route
  '/dash/combo-2': typeof DashCombo2Route
  '/f125/analyse': typeof F125AnalyseRoute
  '/f125/cars': typeof F125CarsRoute
  '/f125/chats': typeof F125ChatsRoute
  '/f125/compare': typeof F125CompareRoute
  '/f125/live': typeof F125LiveRoute
  '/f125/raw': typeof F125RawRoute
  '/f125/sessions': typeof F125SessionsRoute
  '/f125/setup': typeof F125SetupRouteWithChildren
  '/f125/tracks': typeof F125TracksRoute
  '/f125/tunes': typeof F125TunesRouteWithChildren
  '/fm23/analyse': typeof Fm23AnalyseRoute
  '/fm23/cars': typeof Fm23CarsRoute
  '/fm23/chats': typeof Fm23ChatsRoute
  '/fm23/compare': typeof Fm23CompareRoute
  '/fm23/live': typeof Fm23LiveRouteWithChildren
  '/fm23/raw': typeof Fm23RawRoute
  '/fm23/sessions': typeof Fm23SessionsRoute
  '/fm23/setup': typeof Fm23SetupRouteWithChildren
  '/fm23/tracks': typeof Fm23TracksRoute
  '/fm23/tunes': typeof Fm23TunesRouteWithChildren
  '/ac-evo/': typeof AcEvoIndexRoute
  '/acc/': typeof AccIndexRoute
  '/dash/': typeof DashIndexRoute
  '/f125/': typeof F125IndexRoute
  '/fm23/': typeof Fm23IndexRoute
  '/fm23/cars/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/live/driver': typeof Fm23LiveDriverRoute
  '/fm23/live/pit': typeof Fm23LivePitRoute
  '/fm23/setup/$profileId': typeof Fm23SetupProfileIdRoute
  '/fm23/tunes/catalog': typeof Fm23TunesCatalogRoute
  '/fm23/tunes/new': typeof Fm23TunesNewRoute
  '/acc/setup/': typeof AccSetupIndexRoute
  '/f125/setup/': typeof F125SetupIndexRoute
  '/f125/tunes/': typeof F125TunesIndexRoute
  '/fm23/setup/': typeof Fm23SetupIndexRoute
  '/fm23/tunes/': typeof Fm23TunesIndexRoute
  '/fm23/tunes/edit/$tuneId': typeof Fm23TunesEditTuneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/ac-evo/analyse': typeof AcEvoAnalyseRoute
  '/ac-evo/cars': typeof AcEvoCarsRoute
  '/ac-evo/chats': typeof AcEvoChatsRoute
  '/ac-evo/compare': typeof AcEvoCompareRoute
  '/ac-evo/live': typeof AcEvoLiveRoute
  '/ac-evo/raw': typeof AcEvoRawRoute
  '/ac-evo/sessions': typeof AcEvoSessionsRoute
  '/ac-evo/tracks': typeof AcEvoTracksRoute
  '/acc/analyse': typeof AccAnalyseRoute
  '/acc/cars': typeof AccCarsRoute
  '/acc/chats': typeof AccChatsRoute
  '/acc/compare': typeof AccCompareRoute
  '/acc/live': typeof AccLiveRoute
  '/acc/raw': typeof AccRawRoute
  '/acc/sessions': typeof AccSessionsRoute
  '/acc/tracks': typeof AccTracksRoute
  '/dash/combo-1': typeof DashCombo1Route
  '/dash/combo-2': typeof DashCombo2Route
  '/f125/analyse': typeof F125AnalyseRoute
  '/f125/cars': typeof F125CarsRoute
  '/f125/chats': typeof F125ChatsRoute
  '/f125/compare': typeof F125CompareRoute
  '/f125/live': typeof F125LiveRoute
  '/f125/raw': typeof F125RawRoute
  '/f125/sessions': typeof F125SessionsRoute
  '/f125/tracks': typeof F125TracksRoute
  '/fm23/analyse': typeof Fm23AnalyseRoute
  '/fm23/cars': typeof Fm23CarsRoute
  '/fm23/chats': typeof Fm23ChatsRoute
  '/fm23/compare': typeof Fm23CompareRoute
  '/fm23/live': typeof Fm23LiveRouteWithChildren
  '/fm23/raw': typeof Fm23RawRoute
  '/fm23/sessions': typeof Fm23SessionsRoute
  '/fm23/tracks': typeof Fm23TracksRoute
  '/ac-evo': typeof AcEvoIndexRoute
  '/acc': typeof AccIndexRoute
  '/dash': typeof DashIndexRoute
  '/f125': typeof F125IndexRoute
  '/fm23': typeof Fm23IndexRoute
  '/fm23/cars/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/live/driver': typeof Fm23LiveDriverRoute
  '/fm23/live/pit': typeof Fm23LivePitRoute
  '/fm23/setup/$profileId': typeof Fm23SetupProfileIdRoute
  '/fm23/tunes/catalog': typeof Fm23TunesCatalogRoute
  '/fm23/tunes/new': typeof Fm23TunesNewRoute
  '/acc/setup': typeof AccSetupIndexRoute
  '/f125/setup': typeof F125SetupIndexRoute
  '/f125/tunes': typeof F125TunesIndexRoute
  '/fm23/setup': typeof Fm23SetupIndexRoute
  '/fm23/tunes': typeof Fm23TunesIndexRoute
  '/fm23/tunes/edit/$tuneId': typeof Fm23TunesEditTuneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ac-evo': typeof AcEvoRouteWithChildren
  '/acc': typeof AccRouteWithChildren
  '/dev': typeof DevRoute
  '/f125': typeof F125RouteWithChildren
  '/fm23': typeof Fm23RouteWithChildren
  '/ac-evo/analyse': typeof AcEvoAnalyseRoute
  '/ac-evo/cars': typeof AcEvoCarsRoute
  '/ac-evo/chats': typeof AcEvoChatsRoute
  '/ac-evo/compare': typeof AcEvoCompareRoute
  '/ac-evo/live': typeof AcEvoLiveRoute
  '/ac-evo/raw': typeof AcEvoRawRoute
  '/ac-evo/sessions': typeof AcEvoSessionsRoute
  '/ac-evo/tracks': typeof AcEvoTracksRoute
  '/acc/analyse': typeof AccAnalyseRoute
  '/acc/cars': typeof AccCarsRoute
  '/acc/chats': typeof AccChatsRoute
  '/acc/compare': typeof AccCompareRoute
  '/acc/live': typeof AccLiveRoute
  '/acc/raw': typeof AccRawRoute
  '/acc/sessions': typeof AccSessionsRoute
  '/acc/setup': typeof AccSetupRouteWithChildren
  '/acc/tracks': typeof AccTracksRoute
  '/dash/combo-1': typeof DashCombo1Route
  '/dash/combo-2': typeof DashCombo2Route
  '/f125/analyse': typeof F125AnalyseRoute
  '/f125/cars': typeof F125CarsRoute
  '/f125/chats': typeof F125ChatsRoute
  '/f125/compare': typeof F125CompareRoute
  '/f125/live': typeof F125LiveRoute
  '/f125/raw': typeof F125RawRoute
  '/f125/sessions': typeof F125SessionsRoute
  '/f125/setup': typeof F125SetupRouteWithChildren
  '/f125/tracks': typeof F125TracksRoute
  '/f125/tunes': typeof F125TunesRouteWithChildren
  '/fm23/analyse': typeof Fm23AnalyseRoute
  '/fm23/cars': typeof Fm23CarsRoute
  '/fm23/chats': typeof Fm23ChatsRoute
  '/fm23/compare': typeof Fm23CompareRoute
  '/fm23/live': typeof Fm23LiveRouteWithChildren
  '/fm23/raw': typeof Fm23RawRoute
  '/fm23/sessions': typeof Fm23SessionsRoute
  '/fm23/setup': typeof Fm23SetupRouteWithChildren
  '/fm23/tracks': typeof Fm23TracksRoute
  '/fm23/tunes': typeof Fm23TunesRouteWithChildren
  '/ac-evo/': typeof AcEvoIndexRoute
  '/acc/': typeof AccIndexRoute
  '/dash/': typeof DashIndexRoute
  '/f125/': typeof F125IndexRoute
  '/fm23/': typeof Fm23IndexRoute
  '/fm23/cars_/$carOrdinal': typeof Fm23CarsCarOrdinalRoute
  '/fm23/live/driver': typeof Fm23LiveDriverRoute
  '/fm23/live/pit': typeof Fm23LivePitRoute
  '/fm23/setup/$profileId': typeof Fm23SetupProfileIdRoute
  '/fm23/tunes/catalog': typeof Fm23TunesCatalogRoute
  '/fm23/tunes/new': typeof Fm23TunesNewRoute
  '/acc/setup/': typeof AccSetupIndexRoute
  '/f125/setup/': typeof F125SetupIndexRoute
  '/f125/tunes/': typeof F125TunesIndexRoute
  '/fm23/setup/': typeof Fm23SetupIndexRoute
  '/fm23/tunes/': typeof Fm23TunesIndexRoute
  '/fm23/tunes/edit/$tuneId': typeof Fm23TunesEditTuneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ac-evo'
    | '/acc'
    | '/dev'
    | '/f125'
    | '/fm23'
    | '/ac-evo/analyse'
    | '/ac-evo/cars'
    | '/ac-evo/chats'
    | '/ac-evo/compare'
    | '/ac-evo/live'
    | '/ac-evo/raw'
    | '/ac-evo/sessions'
    | '/ac-evo/tracks'
    | '/acc/analyse'
    | '/acc/cars'
    | '/acc/chats'
    | '/acc/compare'
    | '/acc/live'
    | '/acc/raw'
    | '/acc/sessions'
    | '/acc/setup'
    | '/acc/tracks'
    | '/dash/combo-1'
    | '/dash/combo-2'
    | '/f125/analyse'
    | '/f125/cars'
    | '/f125/chats'
    | '/f125/compare'
    | '/f125/live'
    | '/f125/raw'
    | '/f125/sessions'
    | '/f125/setup'
    | '/f125/tracks'
    | '/f125/tunes'
    | '/fm23/analyse'
    | '/fm23/cars'
    | '/fm23/chats'
    | '/fm23/compare'
    | '/fm23/live'
    | '/fm23/raw'
    | '/fm23/sessions'
    | '/fm23/setup'
    | '/fm23/tracks'
    | '/fm23/tunes'
    | '/ac-evo/'
    | '/acc/'
    | '/dash/'
    | '/f125/'
    | '/fm23/'
    | '/fm23/cars/$carOrdinal'
    | '/fm23/live/driver'
    | '/fm23/live/pit'
    | '/fm23/setup/$profileId'
    | '/fm23/tunes/catalog'
    | '/fm23/tunes/new'
    | '/acc/setup/'
    | '/f125/setup/'
    | '/f125/tunes/'
    | '/fm23/setup/'
    | '/fm23/tunes/'
    | '/fm23/tunes/edit/$tuneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/ac-evo/analyse'
    | '/ac-evo/cars'
    | '/ac-evo/chats'
    | '/ac-evo/compare'
    | '/ac-evo/live'
    | '/ac-evo/raw'
    | '/ac-evo/sessions'
    | '/ac-evo/tracks'
    | '/acc/analyse'
    | '/acc/cars'
    | '/acc/chats'
    | '/acc/compare'
    | '/acc/live'
    | '/acc/raw'
    | '/acc/sessions'
    | '/acc/tracks'
    | '/dash/combo-1'
    | '/dash/combo-2'
    | '/f125/analyse'
    | '/f125/cars'
    | '/f125/chats'
    | '/f125/compare'
    | '/f125/live'
    | '/f125/raw'
    | '/f125/sessions'
    | '/f125/tracks'
    | '/fm23/analyse'
    | '/fm23/cars'
    | '/fm23/chats'
    | '/fm23/compare'
    | '/fm23/live'
    | '/fm23/raw'
    | '/fm23/sessions'
    | '/fm23/tracks'
    | '/ac-evo'
    | '/acc'
    | '/dash'
    | '/f125'
    | '/fm23'
    | '/fm23/cars/$carOrdinal'
    | '/fm23/live/driver'
    | '/fm23/live/pit'
    | '/fm23/setup/$profileId'
    | '/fm23/tunes/catalog'
    | '/fm23/tunes/new'
    | '/acc/setup'
    | '/f125/setup'
    | '/f125/tunes'
    | '/fm23/setup'
    | '/fm23/tunes'
    | '/fm23/tunes/edit/$tuneId'
  id:
    | '__root__'
    | '/'
    | '/ac-evo'
    | '/acc'
    | '/dev'
    | '/f125'
    | '/fm23'
    | '/ac-evo/analyse'
    | '/ac-evo/cars'
    | '/ac-evo/chats'
    | '/ac-evo/compare'
    | '/ac-evo/live'
    | '/ac-evo/raw'
    | '/ac-evo/sessions'
    | '/ac-evo/tracks'
    | '/acc/analyse'
    | '/acc/cars'
    | '/acc/chats'
    | '/acc/compare'
    | '/acc/live'
    | '/acc/raw'
    | '/acc/sessions'
    | '/acc/setup'
    | '/acc/tracks'
    | '/dash/combo-1'
    | '/dash/combo-2'
    | '/f125/analyse'
    | '/f125/cars'
    | '/f125/chats'
    | '/f125/compare'
    | '/f125/live'
    | '/f125/raw'
    | '/f125/sessions'
    | '/f125/setup'
    | '/f125/tracks'
    | '/f125/tunes'
    | '/fm23/analyse'
    | '/fm23/cars'
    | '/fm23/chats'
    | '/fm23/compare'
    | '/fm23/live'
    | '/fm23/raw'
    | '/fm23/sessions'
    | '/fm23/setup'
    | '/fm23/tracks'
    | '/fm23/tunes'
    | '/ac-evo/'
    | '/acc/'
    | '/dash/'
    | '/f125/'
    | '/fm23/'
    | '/fm23/cars_/$carOrdinal'
    | '/fm23/live/driver'
    | '/fm23/live/pit'
    | '/fm23/setup/$profileId'
    | '/fm23/tunes/catalog'
    | '/fm23/tunes/new'
    | '/acc/setup/'
    | '/f125/setup/'
    | '/f125/tunes/'
    | '/fm23/setup/'
    | '/fm23/tunes/'
    | '/fm23/tunes/edit/$tuneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcEvoRoute: typeof AcEvoRouteWithChildren
  AccRoute: typeof AccRouteWithChildren
  DevRoute: typeof DevRoute
  F125Route: typeof F125RouteWithChildren
  Fm23Route: typeof Fm23RouteWithChildren
  DashCombo1Route: typeof DashCombo1Route
  DashCombo2Route: typeof DashCombo2Route
  DashIndexRoute: typeof DashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fm23': {
      id: '/fm23'
      path: '/fm23'
      fullPath: '/fm23'
      preLoaderRoute: typeof Fm23RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f125': {
      id: '/f125'
      path: '/f125'
      fullPath: '/f125'
      preLoaderRoute: typeof F125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc': {
      id: '/acc'
      path: '/acc'
      fullPath: '/acc'
      preLoaderRoute: typeof AccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ac-evo': {
      id: '/ac-evo'
      path: '/ac-evo'
      fullPath: '/ac-evo'
      preLoaderRoute: typeof AcEvoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fm23/': {
      id: '/fm23/'
      path: '/'
      fullPath: '/fm23/'
      preLoaderRoute: typeof Fm23IndexRouteImport
      parentRoute: typeof Fm23Route
    }
    '/f125/': {
      id: '/f125/'
      path: '/'
      fullPath: '/f125/'
      preLoaderRoute: typeof F125IndexRouteImport
      parentRoute: typeof F125Route
    }
    '/dash/': {
      id: '/dash/'
      path: '/dash'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc/': {
      id: '/acc/'
      path: '/'
      fullPath: '/acc/'
      preLoaderRoute: typeof AccIndexRouteImport
      parentRoute: typeof AccRoute
    }
    '/ac-evo/': {
      id: '/ac-evo/'
      path: '/'
      fullPath: '/ac-evo/'
      preLoaderRoute: typeof AcEvoIndexRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/fm23/tunes': {
      id: '/fm23/tunes'
      path: '/tunes'
      fullPath: '/fm23/tunes'
      preLoaderRoute: typeof Fm23TunesRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/tracks': {
      id: '/fm23/tracks'
      path: '/tracks'
      fullPath: '/fm23/tracks'
      preLoaderRoute: typeof Fm23TracksRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/setup': {
      id: '/fm23/setup'
      path: '/setup'
      fullPath: '/fm23/setup'
      preLoaderRoute: typeof Fm23SetupRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/sessions': {
      id: '/fm23/sessions'
      path: '/sessions'
      fullPath: '/fm23/sessions'
      preLoaderRoute: typeof Fm23SessionsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/raw': {
      id: '/fm23/raw'
      path: '/raw'
      fullPath: '/fm23/raw'
      preLoaderRoute: typeof Fm23RawRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/live': {
      id: '/fm23/live'
      path: '/live'
      fullPath: '/fm23/live'
      preLoaderRoute: typeof Fm23LiveRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/compare': {
      id: '/fm23/compare'
      path: '/compare'
      fullPath: '/fm23/compare'
      preLoaderRoute: typeof Fm23CompareRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/chats': {
      id: '/fm23/chats'
      path: '/chats'
      fullPath: '/fm23/chats'
      preLoaderRoute: typeof Fm23ChatsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/cars': {
      id: '/fm23/cars'
      path: '/cars'
      fullPath: '/fm23/cars'
      preLoaderRoute: typeof Fm23CarsRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/analyse': {
      id: '/fm23/analyse'
      path: '/analyse'
      fullPath: '/fm23/analyse'
      preLoaderRoute: typeof Fm23AnalyseRouteImport
      parentRoute: typeof Fm23Route
    }
    '/f125/tunes': {
      id: '/f125/tunes'
      path: '/tunes'
      fullPath: '/f125/tunes'
      preLoaderRoute: typeof F125TunesRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/tracks': {
      id: '/f125/tracks'
      path: '/tracks'
      fullPath: '/f125/tracks'
      preLoaderRoute: typeof F125TracksRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/setup': {
      id: '/f125/setup'
      path: '/setup'
      fullPath: '/f125/setup'
      preLoaderRoute: typeof F125SetupRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/sessions': {
      id: '/f125/sessions'
      path: '/sessions'
      fullPath: '/f125/sessions'
      preLoaderRoute: typeof F125SessionsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/raw': {
      id: '/f125/raw'
      path: '/raw'
      fullPath: '/f125/raw'
      preLoaderRoute: typeof F125RawRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/live': {
      id: '/f125/live'
      path: '/live'
      fullPath: '/f125/live'
      preLoaderRoute: typeof F125LiveRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/compare': {
      id: '/f125/compare'
      path: '/compare'
      fullPath: '/f125/compare'
      preLoaderRoute: typeof F125CompareRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/chats': {
      id: '/f125/chats'
      path: '/chats'
      fullPath: '/f125/chats'
      preLoaderRoute: typeof F125ChatsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/cars': {
      id: '/f125/cars'
      path: '/cars'
      fullPath: '/f125/cars'
      preLoaderRoute: typeof F125CarsRouteImport
      parentRoute: typeof F125Route
    }
    '/f125/analyse': {
      id: '/f125/analyse'
      path: '/analyse'
      fullPath: '/f125/analyse'
      preLoaderRoute: typeof F125AnalyseRouteImport
      parentRoute: typeof F125Route
    }
    '/dash/combo-2': {
      id: '/dash/combo-2'
      path: '/dash/combo-2'
      fullPath: '/dash/combo-2'
      preLoaderRoute: typeof DashCombo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/combo-1': {
      id: '/dash/combo-1'
      path: '/dash/combo-1'
      fullPath: '/dash/combo-1'
      preLoaderRoute: typeof DashCombo1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc/tracks': {
      id: '/acc/tracks'
      path: '/tracks'
      fullPath: '/acc/tracks'
      preLoaderRoute: typeof AccTracksRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/setup': {
      id: '/acc/setup'
      path: '/setup'
      fullPath: '/acc/setup'
      preLoaderRoute: typeof AccSetupRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/sessions': {
      id: '/acc/sessions'
      path: '/sessions'
      fullPath: '/acc/sessions'
      preLoaderRoute: typeof AccSessionsRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/raw': {
      id: '/acc/raw'
      path: '/raw'
      fullPath: '/acc/raw'
      preLoaderRoute: typeof AccRawRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/live': {
      id: '/acc/live'
      path: '/live'
      fullPath: '/acc/live'
      preLoaderRoute: typeof AccLiveRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/compare': {
      id: '/acc/compare'
      path: '/compare'
      fullPath: '/acc/compare'
      preLoaderRoute: typeof AccCompareRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/chats': {
      id: '/acc/chats'
      path: '/chats'
      fullPath: '/acc/chats'
      preLoaderRoute: typeof AccChatsRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/cars': {
      id: '/acc/cars'
      path: '/cars'
      fullPath: '/acc/cars'
      preLoaderRoute: typeof AccCarsRouteImport
      parentRoute: typeof AccRoute
    }
    '/acc/analyse': {
      id: '/acc/analyse'
      path: '/analyse'
      fullPath: '/acc/analyse'
      preLoaderRoute: typeof AccAnalyseRouteImport
      parentRoute: typeof AccRoute
    }
    '/ac-evo/tracks': {
      id: '/ac-evo/tracks'
      path: '/tracks'
      fullPath: '/ac-evo/tracks'
      preLoaderRoute: typeof AcEvoTracksRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/sessions': {
      id: '/ac-evo/sessions'
      path: '/sessions'
      fullPath: '/ac-evo/sessions'
      preLoaderRoute: typeof AcEvoSessionsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/raw': {
      id: '/ac-evo/raw'
      path: '/raw'
      fullPath: '/ac-evo/raw'
      preLoaderRoute: typeof AcEvoRawRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/live': {
      id: '/ac-evo/live'
      path: '/live'
      fullPath: '/ac-evo/live'
      preLoaderRoute: typeof AcEvoLiveRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/compare': {
      id: '/ac-evo/compare'
      path: '/compare'
      fullPath: '/ac-evo/compare'
      preLoaderRoute: typeof AcEvoCompareRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/chats': {
      id: '/ac-evo/chats'
      path: '/chats'
      fullPath: '/ac-evo/chats'
      preLoaderRoute: typeof AcEvoChatsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/cars': {
      id: '/ac-evo/cars'
      path: '/cars'
      fullPath: '/ac-evo/cars'
      preLoaderRoute: typeof AcEvoCarsRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/ac-evo/analyse': {
      id: '/ac-evo/analyse'
      path: '/analyse'
      fullPath: '/ac-evo/analyse'
      preLoaderRoute: typeof AcEvoAnalyseRouteImport
      parentRoute: typeof AcEvoRoute
    }
    '/fm23/tunes/': {
      id: '/fm23/tunes/'
      path: '/'
      fullPath: '/fm23/tunes/'
      preLoaderRoute: typeof Fm23TunesIndexRouteImport
      parentRoute: typeof Fm23TunesRoute
    }
    '/fm23/setup/': {
      id: '/fm23/setup/'
      path: '/'
      fullPath: '/fm23/setup/'
      preLoaderRoute: typeof Fm23SetupIndexRouteImport
      parentRoute: typeof Fm23SetupRoute
    }
    '/f125/tunes/': {
      id: '/f125/tunes/'
      path: '/'
      fullPath: '/f125/tunes/'
      preLoaderRoute: typeof F125TunesIndexRouteImport
      parentRoute: typeof F125TunesRoute
    }
    '/f125/setup/': {
      id: '/f125/setup/'
      path: '/'
      fullPath: '/f125/setup/'
      preLoaderRoute: typeof F125SetupIndexRouteImport
      parentRoute: typeof F125SetupRoute
    }
    '/acc/setup/': {
      id: '/acc/setup/'
      path: '/'
      fullPath: '/acc/setup/'
      preLoaderRoute: typeof AccSetupIndexRouteImport
      parentRoute: typeof AccSetupRoute
    }
    '/fm23/tunes/new': {
      id: '/fm23/tunes/new'
      path: '/new'
      fullPath: '/fm23/tunes/new'
      preLoaderRoute: typeof Fm23TunesNewRouteImport
      parentRoute: typeof Fm23TunesRoute
    }
    '/fm23/tunes/catalog': {
      id: '/fm23/tunes/catalog'
      path: '/catalog'
      fullPath: '/fm23/tunes/catalog'
      preLoaderRoute: typeof Fm23TunesCatalogRouteImport
      parentRoute: typeof Fm23TunesRoute
    }
    '/fm23/setup/$profileId': {
      id: '/fm23/setup/$profileId'
      path: '/$profileId'
      fullPath: '/fm23/setup/$profileId'
      preLoaderRoute: typeof Fm23SetupProfileIdRouteImport
      parentRoute: typeof Fm23SetupRoute
    }
    '/fm23/live/pit': {
      id: '/fm23/live/pit'
      path: '/pit'
      fullPath: '/fm23/live/pit'
      preLoaderRoute: typeof Fm23LivePitRouteImport
      parentRoute: typeof Fm23LiveRoute
    }
    '/fm23/live/driver': {
      id: '/fm23/live/driver'
      path: '/driver'
      fullPath: '/fm23/live/driver'
      preLoaderRoute: typeof Fm23LiveDriverRouteImport
      parentRoute: typeof Fm23LiveRoute
    }
    '/fm23/cars_/$carOrdinal': {
      id: '/fm23/cars_/$carOrdinal'
      path: '/cars/$carOrdinal'
      fullPath: '/fm23/cars/$carOrdinal'
      preLoaderRoute: typeof Fm23CarsCarOrdinalRouteImport
      parentRoute: typeof Fm23Route
    }
    '/fm23/tunes/edit/$tuneId': {
      id: '/fm23/tunes/edit/$tuneId'
      path: '/edit/$tuneId'
      fullPath: '/fm23/tunes/edit/$tuneId'
      preLoaderRoute: typeof Fm23TunesEditTuneIdRouteImport
      parentRoute: typeof Fm23TunesRoute
    }
  }
}

interface AcEvoRouteChildren {
  AcEvoAnalyseRoute: typeof AcEvoAnalyseRoute
  AcEvoCarsRoute: typeof AcEvoCarsRoute
  AcEvoChatsRoute: typeof AcEvoChatsRoute
  AcEvoCompareRoute: typeof AcEvoCompareRoute
  AcEvoLiveRoute: typeof AcEvoLiveRoute
  AcEvoRawRoute: typeof AcEvoRawRoute
  AcEvoSessionsRoute: typeof AcEvoSessionsRoute
  AcEvoTracksRoute: typeof AcEvoTracksRoute
  AcEvoIndexRoute: typeof AcEvoIndexRoute
}

const AcEvoRouteChildren: AcEvoRouteChildren = {
  AcEvoAnalyseRoute: AcEvoAnalyseRoute,
  AcEvoCarsRoute: AcEvoCarsRoute,
  AcEvoChatsRoute: AcEvoChatsRoute,
  AcEvoCompareRoute: AcEvoCompareRoute,
  AcEvoLiveRoute: AcEvoLiveRoute,
  AcEvoRawRoute: AcEvoRawRoute,
  AcEvoSessionsRoute: AcEvoSessionsRoute,
  AcEvoTracksRoute: AcEvoTracksRoute,
  AcEvoIndexRoute: AcEvoIndexRoute,
}

const AcEvoRouteWithChildren = AcEvoRoute._addFileChildren(AcEvoRouteChildren)

interface AccSetupRouteChildren {
  AccSetupIndexRoute: typeof AccSetupIndexRoute
}

const AccSetupRouteChildren: AccSetupRouteChildren = {
  AccSetupIndexRoute: AccSetupIndexRoute,
}

const AccSetupRouteWithChildren = AccSetupRoute._addFileChildren(
  AccSetupRouteChildren,
)

interface AccRouteChildren {
  AccAnalyseRoute: typeof AccAnalyseRoute
  AccCarsRoute: typeof AccCarsRoute
  AccChatsRoute: typeof AccChatsRoute
  AccCompareRoute: typeof AccCompareRoute
  AccLiveRoute: typeof AccLiveRoute
  AccRawRoute: typeof AccRawRoute
  AccSessionsRoute: typeof AccSessionsRoute
  AccSetupRoute: typeof AccSetupRouteWithChildren
  AccTracksRoute: typeof AccTracksRoute
  AccIndexRoute: typeof AccIndexRoute
}

const AccRouteChildren: AccRouteChildren = {
  AccAnalyseRoute: AccAnalyseRoute,
  AccCarsRoute: AccCarsRoute,
  AccChatsRoute: AccChatsRoute,
  AccCompareRoute: AccCompareRoute,
  AccLiveRoute: AccLiveRoute,
  AccRawRoute: AccRawRoute,
  AccSessionsRoute: AccSessionsRoute,
  AccSetupRoute: AccSetupRouteWithChildren,
  AccTracksRoute: AccTracksRoute,
  AccIndexRoute: AccIndexRoute,
}

const AccRouteWithChildren = AccRoute._addFileChildren(AccRouteChildren)

interface F125SetupRouteChildren {
  F125SetupIndexRoute: typeof F125SetupIndexRoute
}

const F125SetupRouteChildren: F125SetupRouteChildren = {
  F125SetupIndexRoute: F125SetupIndexRoute,
}

const F125SetupRouteWithChildren = F125SetupRoute._addFileChildren(
  F125SetupRouteChildren,
)

interface F125TunesRouteChildren {
  F125TunesIndexRoute: typeof F125TunesIndexRoute
}

const F125TunesRouteChildren: F125TunesRouteChildren = {
  F125TunesIndexRoute: F125TunesIndexRoute,
}

const F125TunesRouteWithChildren = F125TunesRoute._addFileChildren(
  F125TunesRouteChildren,
)

interface F125RouteChildren {
  F125AnalyseRoute: typeof F125AnalyseRoute
  F125CarsRoute: typeof F125CarsRoute
  F125ChatsRoute: typeof F125ChatsRoute
  F125CompareRoute: typeof F125CompareRoute
  F125LiveRoute: typeof F125LiveRoute
  F125RawRoute: typeof F125RawRoute
  F125SessionsRoute: typeof F125SessionsRoute
  F125SetupRoute: typeof F125SetupRouteWithChildren
  F125TracksRoute: typeof F125TracksRoute
  F125TunesRoute: typeof F125TunesRouteWithChildren
  F125IndexRoute: typeof F125IndexRoute
}

const F125RouteChildren: F125RouteChildren = {
  F125AnalyseRoute: F125AnalyseRoute,
  F125CarsRoute: F125CarsRoute,
  F125ChatsRoute: F125ChatsRoute,
  F125CompareRoute: F125CompareRoute,
  F125LiveRoute: F125LiveRoute,
  F125RawRoute: F125RawRoute,
  F125SessionsRoute: F125SessionsRoute,
  F125SetupRoute: F125SetupRouteWithChildren,
  F125TracksRoute: F125TracksRoute,
  F125TunesRoute: F125TunesRouteWithChildren,
  F125IndexRoute: F125IndexRoute,
}

const F125RouteWithChildren = F125Route._addFileChildren(F125RouteChildren)

interface Fm23LiveRouteChildren {
  Fm23LiveDriverRoute: typeof Fm23LiveDriverRoute
  Fm23LivePitRoute: typeof Fm23LivePitRoute
}

const Fm23LiveRouteChildren: Fm23LiveRouteChildren = {
  Fm23LiveDriverRoute: Fm23LiveDriverRoute,
  Fm23LivePitRoute: Fm23LivePitRoute,
}

const Fm23LiveRouteWithChildren = Fm23LiveRoute._addFileChildren(
  Fm23LiveRouteChildren,
)

interface Fm23SetupRouteChildren {
  Fm23SetupProfileIdRoute: typeof Fm23SetupProfileIdRoute
  Fm23SetupIndexRoute: typeof Fm23SetupIndexRoute
}

const Fm23SetupRouteChildren: Fm23SetupRouteChildren = {
  Fm23SetupProfileIdRoute: Fm23SetupProfileIdRoute,
  Fm23SetupIndexRoute: Fm23SetupIndexRoute,
}

const Fm23SetupRouteWithChildren = Fm23SetupRoute._addFileChildren(
  Fm23SetupRouteChildren,
)

interface Fm23TunesRouteChildren {
  Fm23TunesCatalogRoute: typeof Fm23TunesCatalogRoute
  Fm23TunesNewRoute: typeof Fm23TunesNewRoute
  Fm23TunesIndexRoute: typeof Fm23TunesIndexRoute
  Fm23TunesEditTuneIdRoute: typeof Fm23TunesEditTuneIdRoute
}

const Fm23TunesRouteChildren: Fm23TunesRouteChildren = {
  Fm23TunesCatalogRoute: Fm23TunesCatalogRoute,
  Fm23TunesNewRoute: Fm23TunesNewRoute,
  Fm23TunesIndexRoute: Fm23TunesIndexRoute,
  Fm23TunesEditTuneIdRoute: Fm23TunesEditTuneIdRoute,
}

const Fm23TunesRouteWithChildren = Fm23TunesRoute._addFileChildren(
  Fm23TunesRouteChildren,
)

interface Fm23RouteChildren {
  Fm23AnalyseRoute: typeof Fm23AnalyseRoute
  Fm23CarsRoute: typeof Fm23CarsRoute
  Fm23ChatsRoute: typeof Fm23ChatsRoute
  Fm23CompareRoute: typeof Fm23CompareRoute
  Fm23LiveRoute: typeof Fm23LiveRouteWithChildren
  Fm23RawRoute: typeof Fm23RawRoute
  Fm23SessionsRoute: typeof Fm23SessionsRoute
  Fm23SetupRoute: typeof Fm23SetupRouteWithChildren
  Fm23TracksRoute: typeof Fm23TracksRoute
  Fm23TunesRoute: typeof Fm23TunesRouteWithChildren
  Fm23IndexRoute: typeof Fm23IndexRoute
  Fm23CarsCarOrdinalRoute: typeof Fm23CarsCarOrdinalRoute
}

const Fm23RouteChildren: Fm23RouteChildren = {
  Fm23AnalyseRoute: Fm23AnalyseRoute,
  Fm23CarsRoute: Fm23CarsRoute,
  Fm23ChatsRoute: Fm23ChatsRoute,
  Fm23CompareRoute: Fm23CompareRoute,
  Fm23LiveRoute: Fm23LiveRouteWithChildren,
  Fm23RawRoute: Fm23RawRoute,
  Fm23SessionsRoute: Fm23SessionsRoute,
  Fm23SetupRoute: Fm23SetupRouteWithChildren,
  Fm23TracksRoute: Fm23TracksRoute,
  Fm23TunesRoute: Fm23TunesRouteWithChildren,
  Fm23IndexRoute: Fm23IndexRoute,
  Fm23CarsCarOrdinalRoute: Fm23CarsCarOrdinalRoute,
}

const Fm23RouteWithChildren = Fm23Route._addFileChildren(Fm23RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcEvoRoute: AcEvoRouteWithChildren,
  AccRoute: AccRouteWithChildren,
  DevRoute: DevRoute,
  F125Route: F125RouteWithChildren,
  Fm23Route: Fm23RouteWithChildren,
  DashCombo1Route: DashCombo1Route,
  DashCombo2Route: DashCombo2Route,
  DashIndexRoute: DashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
